Doxygen documentation example: IGenericRepository< T > Interface Template Reference
IGenericRepository< T > Interface Template Reference
Public Member Functions
Task PopulateDb ()
Task< T > GetByIdAsync (string id)
Task< IReadOnlyList< T > > GetAllAsync ()
Task< int > AddAsync (T entity)
Task< int > UpdateAsync (T entity)
Task< int > DeleteAsync (string id)
Detailed Description
Type Constraints
T : class
Definition at line 3 of file IGenericRepository.cs.
Member Function Documentation
AddAsync()
Task< int > AddAsync (T entity)
Referenced by UserController.Add().
DeleteAsync()
Task< int > DeleteAsync (string id)
Referenced by UserController.Delete().
GetAllAsync()
Task< IReadOnlyList< T > > GetAllAsync ()
Referenced by UserController.GetAll().
GetByIdAsync()
Task< T > GetByIdAsync (string id)
Referenced by UserController.GetById().
PopulateDb()
Task PopulateDb ()
Referenced by UserController.PopulateDb().
UpdateAsync()
Task< int > UpdateAsync (T entity)
Referenced by UserController.Update().
The documentation for this interface was generated from the following file:
API/Data/Repositories/IGenericRepository.cs