Doxygen documentation example: UnitOfWork Class Reference
UnitOfWork Class Reference
Public Member Functions
UnitOfWork (Context session)
void BeginTransaction ()
void Commit ()
void Rollback ()
void Dispose ()
void BeginTransaction ()
void Commit ()
void Rollback ()
Properties
Context Session [get]
Properties inherited from IUnitOfWork
Context Session [get]
Detailed Description
Definition at line 5 of file UnitOfWork.cs.
Constructor & Destructor Documentation
UnitOfWork()
UnitOfWork (Context session)
Definition at line 9 of file UnitOfWork.cs.
        {
            Session = session;
        }
References UnitOfWork.Session.
Member Function Documentation
BeginTransaction()
void BeginTransaction ()
Implements IUnitOfWork.
Definition at line 14 of file UnitOfWork.cs.
        {
            Session.Transaction = Session.Connection.BeginTransaction();
        }
References Context.Connection, and UnitOfWork.Session.
Commit()
void Commit ()
Implements IUnitOfWork.
Definition at line 19 of file UnitOfWork.cs.
        {
            Session.Transaction.Commit();
            Dispose();
        }
References UnitOfWork.Dispose(), UnitOfWork.Session, and Context.Transaction.
Dispose()
void Dispose ()
Referenced by UnitOfWork.Commit(), and UnitOfWork.Rollback().
Rollback()
void Rollback ()
Implements IUnitOfWork.
Definition at line 25 of file UnitOfWork.cs.
        {
            Session.Transaction.Rollback();
            Dispose();
        }
References UnitOfWork.Dispose(), UnitOfWork.Session, and Context.Transaction.
Property Documentation
Session
Context Session get
Implements IUnitOfWork.
Definition at line 7 of file UnitOfWork.cs.
{ get; }
Referenced by UnitOfWork.BeginTransaction(), UnitOfWork.Commit(), UnitOfWork.Rollback(), and UnitOfWork.UnitOfWork().
The documentation for this class was generated from the following file:
API/Data/Repositories/UnitOfWork.cs