Doxygen documentation example: IUnitOfWork Interface Reference
IUnitOfWork Interface Reference
Public Member Functions
void BeginTransaction ()
void Commit ()
void Rollback ()
Properties
Context Session [get]
Detailed Description
Definition at line 3 of file IUnitOfWork.cs.
Member Function Documentation
BeginTransaction()
void BeginTransaction ()
Implemented in UnitOfWork.
Referenced by UserRepository.AddAsync(), UserRepository.DeleteAsync(), and UserRepository.UpdateAsync().
Commit()
void Commit ()
Implemented in UnitOfWork.
Referenced by UserRepository.AddAsync(), UserRepository.DeleteAsync(), and UserRepository.UpdateAsync().
Rollback()
void Rollback ()
Implemented in UnitOfWork.
Property Documentation
Session
Context Session get
Implemented in UnitOfWork.
Definition at line 5 of file IUnitOfWork.cs.
{ get; }
Referenced by UserRepository.AddAsync(), UserRepository.DeleteAsync(), UserRepository.GetAllAsync(), UserRepository.GetByIdAsync(), and UserRepository.UpdateAsync().
The documentation for this interface was generated from the following file:
API/Data/Repositories/IUnitOfWork.cs