Doxygen documentation example: MainController Class Reference
MainController Class Reference
Protected Member Functions
bool ValidOperation ()
IActionResult CustomResponse (object result=null)
Protected Attributes
ICollection< string > Errors = new List<string>()
Detailed Description
Definition at line 6 of file MainController.cs.
Member Function Documentation
CustomResponse()
IActionResult CustomResponse (object result = null) protected
Definition at line 15 of file MainController.cs.
        {
            if(ValidOperation() && result != null) return Ok(result);
            return BadRequest(new ValidationProblemDetails(new Dictionary<string, string[]>
            {
                { "Messages: ", Errors.ToArray() }
            }));
        }
References MainController.Errors, and MainController.ValidOperation().
Referenced by UserController.Add(), UserController.GetAll(), and UserController.GetById().
ValidOperation()
bool ValidOperation () protected
Definition at line 10 of file MainController.cs.
        {
            return !Errors.Any();
        }
References MainController.Errors.
Referenced by MainController.CustomResponse().
Member Data Documentation
Errors
ICollection<string> Errors = new List<string>() protected
Definition at line 8 of file MainController.cs.
Referenced by MainController.CustomResponse(), and MainController.ValidOperation().
The documentation for this class was generated from the following file:
API/Controllers/MainController.cs