Doxygen documentation example: UserController Class Reference
UserController Class Reference
Public Member Functions
UserController (IUnitOfWork unitOfWork)
async Task< IActionResult > PopulateDb ()
async Task< IActionResult > GetAll ()
async Task< IActionResult > GetById (string id)
async Task< IActionResult > Add (User users)
async Task< IActionResult > Delete (string id)
async Task< IActionResult > Update (User user)
Private Attributes
readonly IUnitOfWork unitOfWork
Additional Inherited Members
Protected Member Functions inherited from MainController
bool ValidOperation ()
IActionResult CustomResponse (object result=null)
Protected Attributes inherited from MainController
ICollection< string > Errors = new List<string>()
Detailed Description
Definition at line 8 of file UserController.cs.
Constructor & Destructor Documentation
UserController()
UserController (IUnitOfWork unitOfWork)
Definition at line 14 of file UserController.cs.
        {
            //_usersRepository = usersRepository;
            this.unitOfWork = unitOfWork;
        }
References UserController.unitOfWork.
Member Function Documentation
Add()
async Task< IActionResult > Add (User users)
Definition at line 45 of file UserController.cs.
        {
            var data = await unitOfWork.Users.AddAsync(users);
            //return Ok(data);
            return data == null ? NotFound() : CustomResponse(data);
        }
References IGenericRepository< T >.AddAsync(), MainController.CustomResponse(), UserController.unitOfWork, and IUnitOfWork.Users.
Delete()
async Task< IActionResult > Delete (string id)
Definition at line 53 of file UserController.cs.
        {
            var data = await unitOfWork.Users.DeleteAsync(id);
            return Ok(data);
        }
References IGenericRepository< T >.DeleteAsync(), UserController.unitOfWork, and IUnitOfWork.Users.
GetAll()
async Task< IActionResult > GetAll ()
Definition at line 28 of file UserController.cs.
        {
            var data = await unitOfWork.Users.GetAllAsync();
            //return Ok(data);
            return data == null ? NotFound() : CustomResponse(data);
        }
References MainController.CustomResponse(), IGenericRepository< T >.GetAllAsync(), UserController.unitOfWork, and IUnitOfWork.Users.
GetById()
async Task< IActionResult > GetById (string id)
Definition at line 36 of file UserController.cs.
        {
            var data = await unitOfWork.Users.GetByIdAsync(id);
            //if (data == null) return Ok();
            //return Ok(data);
            return data == null ? NotFound() : CustomResponse(data);
        }
References MainController.CustomResponse(), IGenericRepository< T >.GetByIdAsync(), UserController.unitOfWork, and IUnitOfWork.Users.
PopulateDb()
async Task< IActionResult > PopulateDb ()
Definition at line 21 of file UserController.cs.
        {
            var users = unitOfWork.Users.PopulateDb();
            return Ok();
        }
References IGenericRepository< T >.PopulateDb(), UserController.unitOfWork, and IUnitOfWork.Users.
Update()
async Task< IActionResult > Update (User user)
Definition at line 60 of file UserController.cs.
        {
            var data = await unitOfWork.Users.UpdateAsync(user);
            return Ok(data);
        }
References UserController.unitOfWork, IGenericRepository< T >.UpdateAsync(), and IUnitOfWork.Users.
Member Data Documentation
unitOfWork
readonly IUnitOfWork unitOfWork private
Definition at line 11 of file UserController.cs.
Referenced by UserController.Add(), UserController.Delete(), UserController.GetAll(), UserController.GetById(), UserController.PopulateDb(), UserController.Update(), and UserController.UserController().
The documentation for this class was generated from the following file:
API/Controllers/UserController.cs