Doxygen documentation example: Context Class Reference
Context Class Reference
Public Member Functions
Context (IConfiguration config)
IDbConnection GetDbConnection ()
Private Attributes
IConfiguration _config
Detailed Description
Definition at line 7 of file Context.cs.
Constructor & Destructor Documentation
Context()
Context (IConfiguration config)
Definition at line 15 of file Context.cs.
        {
            this._config = config;
            //this._conn = conn;
            //this._connString = this._config.GetConnectionString("Default").ToString();
        }
Member Function Documentation
GetDbConnection()
IDbConnection GetDbConnection ()
Referenced by UserRepository.AddAsync(), Database.CreateDatabase(), UserRepository.DeleteAsync(), UserRepository.GetAllAsync(), UserRepository.GetByIdAsync(), and UserRepository.UpdateAsync().
Member Data Documentation
_config
IConfiguration _config private
Definition at line 10 of file Context.cs.
The documentation for this class was generated from the following file:
API/Data/Context.cs