Doxygen documentation example: UserRepository Class Reference
UserRepository Class Reference
Public Member Functions
UserRepository (IUnitOfWork unitOfWork)
async Task PopulateDb ()
async Task< int > AddAsync (User entity)
async Task< int > AddAsync (List< User > entity)
async Task< int > DeleteAsync (string id)
async Task< IReadOnlyList< User > > GetAllAsync ()
async Task< User > GetByIdAsync (string id)
async Task< int > UpdateAsync (User entity)
async Task< int > UpdateAsync (List< User > entity)
Public Member Functions inherited from IGenericRepository< User >
Task PopulateDb ()
Task< T > GetByIdAsync (string id)
Task< IReadOnlyList< T > > GetAllAsync ()
Task< int > AddAsync (T entity)
Task< int > AddAsync (List< T > entity)
Task< int > UpdateAsync (T entity)
Task< int > UpdateAsync (List< T > entity)
Task< int > DeleteAsync (string id)
Private Attributes
readonly IUnitOfWork _unitOfWork
Detailed Description
Definition at line 7 of file UserRepository.cs.
Constructor & Destructor Documentation
UserRepository()
UserRepository (IUnitOfWork unitOfWork)
Definition at line 11 of file UserRepository.cs.
        {
            _unitOfWork = unitOfWork;
        }
References UserRepository._unitOfWork.
Member Function Documentation
AddAsync() [1/2]
async Task< int > AddAsync (List< User > entity)
Definition at line 51 of file UserRepository.cs.
        {
            var sql = "Insert into Users (Id, Name, Email, WebSite, Followers, Area, Bio) VALUES (@Id, @Name, @Email, @WebSite, @Followers, @Area, @Bio)";
            int result = 0;
            using (var connection = _unitOfWork.Session.Connection)
            {
                _unitOfWork.BeginTransaction();
                foreach (var user in entity)
                {
                    user.Id = Guid.NewGuid().ToString();
                    result = await connection.ExecuteAsync(sql, user);
                }
                _unitOfWork.Commit();
                return result;
            }
        }
References UserRepository._unitOfWork, IUnitOfWork.BeginTransaction(), IUnitOfWork.Commit(), Context.Connection, and IUnitOfWork.Session.
AddAsync() [2/2]
async Task< int > AddAsync (User entity)
Definition at line 38 of file UserRepository.cs.
        {
            entity.Id = Guid.NewGuid().ToString();
            var sql = "Insert into Users (Id, Name, Email, WebSite, Followers, Area, Bio) VALUES (@Id, @Name, @Email, @WebSite, @Followers, @Area, @Bio)";
            using (var connection = _unitOfWork.Session.Connection)
            {
                _unitOfWork.BeginTransaction();
                var result = await connection.ExecuteAsync(sql, entity);
                _unitOfWork.Commit();
                return result;
            }
        }
References UserRepository._unitOfWork, IUnitOfWork.BeginTransaction(), IUnitOfWork.Commit(), Context.Connection, and IUnitOfWork.Session.
Referenced by UserRepository.PopulateDb().
DeleteAsync()
async Task< int > DeleteAsync (string id)
Definition at line 68 of file UserRepository.cs.
        {
            var sql = "DELETE FROM Users WHERE Id = @Id";
            using (var connection = _unitOfWork.Session.Connection)
            {
                _unitOfWork.BeginTransaction();
                var result = await connection.ExecuteAsync(sql, new { Id = id });
                _unitOfWork.Commit();
                return result;
            }
        }
References UserRepository._unitOfWork, IUnitOfWork.BeginTransaction(), IUnitOfWork.Commit(), Context.Connection, and IUnitOfWork.Session.
GetAllAsync()
async Task< IReadOnlyList< User > > GetAllAsync ()
Definition at line 80 of file UserRepository.cs.
        {
            var sql = "SELECT * FROM Users";
            using (var connection = _unitOfWork.Session.Connection)
            {
                var result = await connection.QueryAsync<User>(sql);
                return result.ToList();
            }
        }
References UserRepository._unitOfWork, Context.Connection, and IUnitOfWork.Session.
GetByIdAsync()
async Task< User > GetByIdAsync (string id)
Definition at line 90 of file UserRepository.cs.
        {
            var sql = "SELECT * FROM Users WHERE Id = @Id";
            using (var connection = _unitOfWork.Session.Connection)
            {
                var result = await connection.QuerySingleOrDefaultAsync<User>(sql, new { Id = id });
                return result;
            }
        }
References UserRepository._unitOfWork, Context.Connection, and IUnitOfWork.Session.
PopulateDb()
async Task PopulateDb ()
Definition at line 16 of file UserRepository.cs.
        {
            var users = new List<User>();
            for (int i = 0; i < 10; i++)
            {
                var user = new User();
                user.Id = "";
                user.Name = Faker.Name.FullName();
                user.Email = Faker.Internet.Email(user.Name);
                user.WebSite = Faker.Internet.DomainName();
                user.Area = $"{Faker.Address.Country()}, {Faker.Address.City()}";
                user.Followers = Faker.RandomNumber.Next(0, 10000);
                user.Bio = String.Join(" ", Faker.Lorem.Sentences(3));
                users.Add(user);
            }
            await AddAsync(users);
        }
References UserRepository.AddAsync().
UpdateAsync() [1/2]
async Task< int > UpdateAsync (List< User > entity)
Definition at line 112 of file UserRepository.cs.
        {
            var sql = "UPDATE Users SET Name = @Name, Email = @Email, WebSite = @WebSite, Followers = @Followers, Area = @Area, Bio = @Bio  WHERE Id = @Id";
            int result = 0;
            using (var connection = _unitOfWork.Session.Connection)
            {
                _unitOfWork.BeginTransaction();
                foreach (var user in entity)
                    result = await connection.ExecuteAsync(sql, user);
                _unitOfWork.Commit();
                return result;
            }
        }
References UserRepository._unitOfWork, IUnitOfWork.BeginTransaction(), IUnitOfWork.Commit(), Context.Connection, and IUnitOfWork.Session.
UpdateAsync() [2/2]
async Task< int > UpdateAsync (User entity)
Definition at line 100 of file UserRepository.cs.
        {
            var sql = "UPDATE Users SET Name = @Name, Email = @Email, WebSite = @WebSite, Followers = @Followers, Area = @Area, Bio = @Bio  WHERE Id = @Id";
            using (var connection = _unitOfWork.Session.Connection)
            {
                _unitOfWork.BeginTransaction();
                var result = await connection.ExecuteAsync(sql, entity);
                _unitOfWork.Commit();
                return result;
            }
        }
References UserRepository._unitOfWork, IUnitOfWork.BeginTransaction(), IUnitOfWork.Commit(), Context.Connection, and IUnitOfWork.Session.
Member Data Documentation
_unitOfWork
readonly IUnitOfWork _unitOfWork private
Definition at line 9 of file UserRepository.cs.
Referenced by UserRepository.AddAsync(), UserRepository.DeleteAsync(), UserRepository.GetAllAsync(), UserRepository.GetByIdAsync(), UserRepository.UpdateAsync(), and UserRepository.UserRepository().
The documentation for this class was generated from the following file:
API/Data/Repositories/UserRepository.cs